/* Sandbox v6. Share's vendored model-viewer and gold loader, public 906 GLB.
   Material split is made in the scoped GLB, never in the source or Live assets.
   ASSUMED: full-square public mock art follows the existing UVs; logo/text placement
   is a local preview composition, not recovered historical Clay print geometry. */
(function(){
'use strict';
var BASE='../assets/models/start227/', stage, viewer, loader, error, picture, asset='', token=0, record, applied='', film=0, real=0, loaded=false, leaving=false, frame=0, unbranded=false, originals=[], mounted=false, filmGeneration=0, exitTimers=[];
var models={'candle-906':'gift-906.glb','yeti-tumbler':'yeti-tumbler.glb','yeti-travel-mug':'yeti-travel-mug.glb','stanley-quencher':'stanley-quencher.glb','ember-mug':'ember-mug.glb','yeti-lowball':'yeti-lowball.glb'};
var images=new Map(), ready=Promise.all([fetch('start-227-assets/sb-loader.html').then(function(r){if(!r.ok)throw Error('Share loader unavailable');return r.text();}),new Promise(function(resolve,reject){if(customElements.get('model-viewer'))return resolve();var s=document.createElement('script');s.type='module';s.src='../assets/vendor/model-viewer/model-viewer.min.js';s.onload=function(){customElements.whenDefined('model-viewer').then(resolve);};s.onerror=reject;document.head.appendChild(s);})]).then(function(results){
 customElements.get('model-viewer').dracoDecoderLocation=new URL('../assets/vendor/model-viewer/draco/',location.href).href;
 stage=document.createElement('div');stage.className='sb-scene-stage';stage.innerHTML='<model-viewer camera-controls touch-action="none" interaction-prompt="none" loading="eager" reveal="manual" exposure="1.05" shadow-intensity="1.1" shadow-softness="0.9" environment-image="neutral" camera-orbit="8deg 25deg 105%" camera-target="auto auto auto" field-of-view="30deg" min-field-of-view="18deg" max-field-of-view="45deg" aria-label="Interactive gift design"></model-viewer>'+results[0]+'<div class="sb-scene-error" hidden><p>We couldn’t load this gift preview.</p><button class="gb-btn gb-btn--ghost gb-btn--secondary" type="button">Try again</button></div><img class="sb-scene-photo" hidden alt="Gift product photo">';
 viewer=stage.querySelector('model-viewer');loader=stage.querySelector('.gbds-loader');error=stage.querySelector('.sb-scene-error');picture=stage.querySelector('.sb-scene-photo');
 var sparks=loader.querySelector('.gbds-loader__particles'),angle=347,dist=383,delay=6.9;
 for(var i=0;i<40;i++){var particle=document.createElement('span');particle.className='gbds-loader__particle';particle.style.cssText='--angle:'+((angle%360+360)%360)+'deg;--distance:'+dist+'px;--size:'+(i%2===0?2:1)+'px;--delay:'+(Math.round(delay*10)/10)+'s;--duration:5s;--start-offset:'+(38-2*(i%15))+'px';sparks.appendChild(particle);angle-=13;dist-=67;if(dist<208)dist+=250;delay-=1.1;if(delay<0)delay+=8;}
 error.querySelector('button').onclick=function(){asset='';mount(stage.parentElement,record);};
 viewer.addEventListener('progress',function(e){real=e.detail.totalProgress;});
 viewer.addEventListener('load',function(){loaded=true;real=1;originals=viewer.model.materials.map(function(m){return {material:m,texture:m.pbrMetallicRoughness.baseColorTexture.texture,factor:Array.from(m.pbrMetallicRoughness.baseColorFactor)};});update(record);});
 viewer.addEventListener('error',function(){token++;loader.hidden=true;error.hidden=false;stage.dataset.status='error';});
 // Share native orbit/zoom/touch controls; Shift+drag pans camera target as the declared hint says.
 var pan=null;
 viewer.addEventListener('pointerdown',function(e){if(!e.shiftKey||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();pan={id:e.pointerId,x:e.clientX,y:e.clientY,target:viewer.getCameraTarget(),orbit:viewer.getCameraOrbit()};viewer.setPointerCapture(e.pointerId);},true);
 viewer.addEventListener('pointermove',function(e){if(!pan||pan.id!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();var s=pan.orbit.radius/stage.clientHeight,dx=(e.clientX-pan.x)*s,dy=(e.clientY-pan.y)*s,t=pan.target,o=pan.orbit;viewer.cameraTarget=(t.x-dx*Math.cos(o.theta))+'m '+(t.y+dy)+'m '+(t.z+dx*Math.sin(o.theta))+'m';},true);
 viewer.addEventListener('pointerup',function(e){if(pan){e.stopImmediatePropagation();pan=null;}},true);
 return true;
});
function image(src){if(!images.has(src))images.set(src,new Promise(function(resolve,reject){var i=new Image();i.onload=function(){resolve(i);};i.onerror=function(){reject(Error('Texture unavailable: '+src));};i.src=src;}));return images.get(src);}
function resetFilm(){filmGeneration++;exitTimers.forEach(clearTimeout);exitTimers=[];film=performance.now();real=0;loaded=false;leaving=false;loader.hidden=false;loader.classList.remove('is-leaving','is-gone');error.hidden=true;stage.dataset.status='loading';cancelAnimationFrame(frame);tick();}
function tick(){if(!mounted||!stage.isConnected)return;var shown=Math.min(real,Math.max(0,Math.min(1,(performance.now()-film-1200)/2400)));loader.querySelector('.gbds-loader__bar').style.width=(shown*100)+'%';loader.querySelector('.gbds-loader__pct').textContent=Math.round(shown*100)+'%';loader.querySelector('.gbds-loader__glow').style.left=(shown*100)+'%';if(loaded&&applied&&shown===1&&!leaving){leaving=true;loader.classList.add('is-leaving');var fg=filmGeneration;exitTimers.push(setTimeout(function(){if(!mounted||fg!==filmGeneration||!leaving)return;viewer.dismissPoster();loader.classList.add('is-gone');stage.dataset.status='ready';exitTimers.push(setTimeout(function(){if(mounted&&fg===filmGeneration&&leaving)loader.hidden=true;},1700));},2000));}else if(!leaving)frame=requestAnimationFrame(tick);}
function signature(d){return JSON.stringify([d.id,d.tile,d.fields]);}
async function compose(d,surface){var c=document.createElement('canvas');c.width=c.height=1024;var ctx=c.getContext('2d'),f=d.fields;
 if(surface==='card'){ctx.fillStyle='#fafafa';ctx.fillRect(0,0,1024,1024);}else{ctx.drawImage(await image(BASE+'art-'+d.tile+'-'+surface+'.webp'),0,0,1024,1024);if(f[surface+'Changed']){ctx.save();ctx.globalAlpha=.8;ctx.fillStyle=f[surface];ctx.fillRect(0,0,1024,1024);ctx.restore();}}
 var logo=surface==='card'?f.cardLogo:surface==='lid'?f.boxLogo:0,mode=surface==='card'?f.cardMode:f.boxMode;
 if(logo){var img=await image('start-227-assets/img/cz-logo-'+logo+'.png');ctx.save();if(mode==='Monochrome')ctx.filter='grayscale(1)';var w=logo===1?(surface==='card'?180:160):90,h=w*img.height/img.width;ctx.drawImage(img,512-w/2,surface==='card'?330:500-h/2,w,h);ctx.restore();}
 ctx.fillStyle='#18181b';ctx.textAlign='center';ctx.font='400 24px Inter, sans-serif';
 if(surface==='lid'&&f.name)ctx.fillText(f.name,512,580,480);
 if(surface==='card'){ctx.fillText(f.intro||'',512,425,800);ctx.font='300 18px Inter, sans-serif';var words=(f.message||'').split(/\s+/),line='',lines=[];words.forEach(function(w){var next=line+' '+w;if(ctx.measureText(next).width>740){lines.push(line);line=w;}else line=next;});lines.push(line);lines.slice(0,8).forEach(function(l,i){ctx.fillText(l.trim(),512,465+i*24);});ctx.font='400 20px Inter, sans-serif';ctx.fillText(f.signature||'',512,690,800);}
 return c.toDataURL('image/png');
}
async function update(d){if(!d||!viewer||!loaded||!stage.isConnected)return;record=d;var mine=++token,sig=signature(d);if(unbranded){originals.forEach(function(o){o.material.pbrMetallicRoughness.baseColorTexture.setTexture(o.texture);o.material.pbrMetallicRoughness.setBaseColorFactor(o.factor);});applied='unbranded';stage.dataset.design='unbranded';stage.dataset.mode='unbranded';delete stage.dataset.tile;delete stage.dataset.textureSignature;window.GBSandboxScene.binding={designId:d.id,giftId:d.gift.id,mode:'unbranded'};tick();return;}stage.dataset.mode='branded';if(sig===applied)return;if(d.gift.id!=='candle-906'){applied=sig;stage.dataset.design=d.id;window.GBSandboxScene.binding={designId:d.id,giftId:d.gift.id,tile:d.tile,mode:'original-product',model:asset};tick();return;}
 var snapshot=JSON.parse(JSON.stringify(d));try{var urls=await Promise.all(['lid','tray','card'].map(function(k){return compose(snapshot,k);}));if(mine!==token||!mounted)return;var textures=await Promise.all(urls.map(function(u){return viewer.createTexture(u);}));if(mine!==token||!stage.isConnected||!record||signature(record)!==sig)return;
  var groups=[['SB_Lid','B-GB-WRAP-LID-240x100x96-V003'],['SB_Tray','B-GB-WRAP-TRAY-240x100x96-V003'],['SB_Card','Material _29']];
  groups.forEach(function(names,i){viewer.model.materials.filter(function(m){return names.indexOf(m.name)>=0;}).forEach(function(m){m.pbrMetallicRoughness.baseColorTexture.setTexture(textures[i]);m.pbrMetallicRoughness.setBaseColorFactor([1,1,1,1]);});});
  applied=sig;stage.dataset.design=d.id;stage.dataset.tile=d.tile;stage.dataset.textureSignature=sig;window.GBSandboxScene.binding={designId:d.id,tile:d.tile,lidMaterial:'SB_Lid',trayMaterial:'SB_Tray',cardMaterial:'SB_Card',signatures:urls.map(function(u){var h=0;for(var i=0;i<u.length;i++)h=(Math.imul(h,31)+u.charCodeAt(i))|0;return h;})};tick();
 }catch(e){if(mine===token){loader.hidden=true;error.hidden=false;stage.dataset.status='error';console.error(e);}}
}
function mount(host,d,reading){if(!stage||!host||!d)return;var resumed=!mounted;mounted=true;unbranded=!!reading;record=d;host.classList.add('sb-real-scene');host.appendChild(stage);var next=models[d.gift.id];picture.hidden=!!next;viewer.hidden=!next;if(!next){token++;filmGeneration++;cancelAnimationFrame(frame);exitTimers.forEach(clearTimeout);exitTimers=[];leaving=false;window.GBSandboxScene.binding={designId:d.id,giftId:d.gift.id,mode:'photo'};picture.src=d.gift.scene;picture.alt=d.gift.name;loader.hidden=true;error.hidden=true;stage.dataset.status='photo';stage.dataset.design=d.id;return;}
 var nextURL=BASE+next;if(nextURL!==asset){token++;asset=nextURL;applied='';resetFilm();viewer.cameraOrbit='8deg 25deg 105%';viewer.src=nextURL;}else if(loaded){if(resumed&&!loader.hidden){leaving=false;loader.classList.remove('is-leaving','is-gone');film=performance.now();tick();}update(d);}
}
window.GBSandboxScene={ready:ready,mount:mount,update:update,unmount:function(){token++;mounted=false;filmGeneration++;cancelAnimationFrame(frame);exitTimers.forEach(clearTimeout);exitTimers=[];if(stage)stage.remove();},viewer:function(){return viewer;},binding:null,models:models};
})();
